TEMPLATE = subdirs
SUBDIRS += cmake \
    qknxadditionalinfo \
    qknxaddress \
    qknxnetipconfigdib \
    qknxnetipconnectionheader \
    qknxnetipconnectionstaterequest \
    qknxnetipconnectionstateresponse \
    qknxnetipconnectrequest \
    qknxnetipconnectresponse \
    qknxnetipcrd \
    qknxnetipcri \
    qknxnetipcurrentconfigdib \
    qknxnetipdescriptionrequest \
    qknxnetipdescriptionresponse \
    qknxnetipdeviceconfigurationacknowledge \
    qknxnetipdeviceconfigurationrequest \
    qknxnetipdevicedib \
    qknxnetipdisconnectrequest \
    qknxnetipdisconnectresponse \
    qknxnetiphpai \
    qknxnetipknxaddressesdib \
    qknxnetipmanufacturerdib \
    qknxnetiproutingbusy \
    qknxnetiproutingindication \
    qknxnetiproutinglostmessage \
    qknxnetipsearchrequest \
    qknxnetipsearchresponse \
    qknxnetipservicefamiliesdib \
    qknxnetipstructure \
    qknxnetiptunnelingacknowledge \
    qknxnetiptunnelingrequest \
    qknxtunnelframe \
    qknxnpdufactory \
    qknxdevicemanagementframe \
    qknxcontrolfield \
    qknxtunnelframefactory \
    qknxdatapointtype \
    qknxproject \
    qknxtransportlayerstatemachine \
    qknxgroupaddressinfo
